### ISSUE TITLE
findByCoach usefullness

### ISSUE THREAD

**Issue by tudor-stoica** [ICS4U-Gallo/4u-cpt-1-man-team#2]
I do not see a point in findByCoach. Should it be removed?

**Comment by MrGallo** [comment]
Coaches need to see a list of their teams to update. The system needs to grab a list of teams based on the coach's email (for the current school year).  Check out the [@DbArray documentation](http://ebean-orm.github.io/docs/mapping/extension/dbarray), specifically the `Expressions` section to see how you can search for all teams based on the DbArray field (coach email).
